image: go1.2
env:
  - GOROOT=/usr/local/go
script:
  - go get github.com/oschwald/geoip2-golang
  - go get github.com/gorilla/mux
  - go install geoip-3fs
notify:
  email:
    recipients:
      - igor.ajdisek@gmail.com
