image: go1.2
env:
  - GOROOT=/usr/local/go
  - GOPATH=$PWD/project
script:
  - make build
deploy:
  ssh:
    target: geoip@188.226.235.163:/home/geoip/releases/
    artifacts:
      - geoip-lookup-${DRONE_COMMIT:0:7}.tar.gz
notify:
  email:
    recipients:
      - igor.ajdisek@gmail.com
